unbind C-b

set -g set-clipboard external
set -g allow-passthrough on

set -as terminal-features ',xterm-256color:clipboard'

set-option -g prefix C-Space
bind-key C-Space send-prefix

set -g @plugin 'tmux-plugins/tmux-resurrect'
set -g @plugin 'tmux-plugins/tmux-continuum'
set -g @plugin 'tmux-plugins/tmux-yank'
set -g @plugin 'jaclu/tmux-menus'
set -g @plugin 'tmux-plugins/tmux-prefix-highlight'

set -g @prefix_highlight_bg 'blue'  # default is 'colour04'
set -g status-right '#{prefix_highlight} | %a %Y-%m-%d %H:%M'

if-shell '[ -n "$SSH_CONNECTION" ]' \
  'set -g mouse off' \
  'set -g mouse on'

set-window-option -g mode-keys vi
set-option -g renumber-windows on

run '~/.tmux/plugins/tpm/tpm'
