#!/usr/bin/env bash
set -e

DOTFILES="$HOME/dotfiles"

link() {
  local src="$1"
  local dest="$2"

  if [ -e "$dest" ] && [ ! -L "$dest" ]; then
    echo "Backing up existing file: $dest to $dest.bak"
    mv "$dest" "$dest.bak"
  fi

  ln -sf "$src" "$dest"
}

link "$DOTFILES/shell/zshrc"     "$HOME/.zshrc"
link "$DOTFILES/shell/bashrc"  "$HOME/.bashrc"
link "$DOTFILES/shell/tmux.conf"  "$HOME/.tmux.conf"
link "$DOTFILES/editor/ideavimrc"  "$HOME/.ideavimrc"

echo "Symlinked dotfiles successfully."
ls -la $HOME | awk '/^l/ {print $9 " -> " $11}'

# link "$DOTFILES/git/gitconfig"   "$HOME/.gitconfig"
# link "$DOTFILES/vim/vimrc"       "$HOME/.vimrc"
